### ISSUE TITLE
Changes re: tee still failing on Windows+MSYS2 in GitHub Actions

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nimbus-build-system#36]
Following from the discussion in status-im/nim-chronos#255, the changes in f85ad74a0516db1abb8839714cd2330d82eed9fa don't result in successful `make update` on Windows+MSYS2 in GitHub Actions.

[L88](https://github.com/status-im/nimbus-build-system/blob/master/makefiles/targets.mk#L88) in `targets.mk` is failing:

https://github.com/michaelsbradleyjr/nbs-proj-1/runs/4873914577?check_suite_focus=true#step:8:15

**Comment by stefantalpalaru** [comment]
UCRT64 is not tested and not supported. Use Mingw-w64.

Also, run `make status` before `make update`, to see what's changed.

**Comment by michaelsbradleyjr** [comment]
MSYS2's UCRT64 environment is generally preferable now and in the future: MSVCRT in MINGW64/32 is old and hacky and doesn't properly support UTF-8:

https://www.msys2.org/docs/environments/

That being said, I'll try MSYS2's MINGW64 environment to see if it makes a difference... very doubtful: I've been chatting with the MSYS2 folks on their discord and it's been suggested that in GHA a cygwin pty has likely not been created as would be the case when launching an MSYS2 environment in Mintty.

**Comment by michaelsbradleyjr** [comment]
Fails the same way with MINGW64:

https://github.com/michaelsbradleyjr/nbs-proj-1/runs/4874190631?check_suite_focus=true#step:8:14

For now, especially in this context (fresh clone in CI, etc.), I can just use `OVERRIDE=1`.

**Comment by stefantalpalaru** [comment]
Mystery solved: you need `OVERRIDE=1` because you do a recursive submodule checkout here: https://github.com/michaelsbradleyjr/nbs-proj-1/blob/65c49d1902f0fe07485cbd2cf03102bd5f5284c1/.github/workflows/issues.yml#L67

`git status` inside submodules picks this up on Windows and sees everything as modified: https://github.com/stefantalpalaru/nbs-proj-1/runs/4874359088?check_suite_focus=true

Could be Git's line ending translation having different settings during that checkout action and later.
